import Main from '../components/Main';
import Head from 'next/head';
import CategoryLinks from '../components/CategoryLinks';
import Hero from '../components/Hero';
import { NextPage } from 'next';
import styles from '../styles/css/home.module.css';
import SeeProduct from '../components/SeeProduct';
import { GetStaticProps } from 'next';
import Image from 'next/image';
import Gear from '../components/Gear';

interface Data{
  name: string;
  slug: string;
  image: {
    desktop: string;
  };
  description: string;
};

export const getStaticProps:GetStaticProps = async () =>{
  const res = await fetch('https://jsonkeeper.com/b/H28U');
  const data = await res.json();
  return {props: {data}};
}
const Home: NextPage<{data: Data[]}> = ({data}) => {
   return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Hero />
        <Main>
          <CategoryLinks />
          <section className={styles.home_products}>
            <div className={styles.zx9}>
              <div className={styles.circles}>
                <Image src={'/assets/home/desktop/pattern-circles.svg'} layout={'responsive'} width={1} height={1}/>
              </div>
              <div className={styles.zx9_image}>
                <Image src={'/assets/home/desktop/image-speaker-zx9.png'} width={300} height={400}/>
              </div>
              <div className={styles.zx9_info}>
                <h2>zx9 speaker</h2>
                <p>Upgrade to premium speakers that are phenomenally built to deliver truly remarkable sound.</p>
                <SeeProduct href={'/speakers/zx9-speaker'} bg={'black'}/>
              </div>
            </div>
            <div className={styles.zx7}>
              <h3>zx7 speaker</h3>
              <SeeProduct href={'/speakers/zx7-speaker'} bg={'transparent'}/>
              <Image src={'/assets/home/tablet/image-speaker-zx7.jpg'} layout={'fill'} objectFit={'cover'} objectPosition={'left'} quality={80}/>
            </div>
            <div className={styles.yx1}>
              <div className={styles.yx1_image}>
                <Image src={'/assets/home/tablet/image-earphones-yx1.jpg'} layout={'fill'} objectFit={'cover'} />
              </div>
              <div className={styles.yx1_info}>
                <h3>yx1 earphones</h3>
                <SeeProduct href={'/earphones/yx1-earphones'} bg={'transparent'}/>
              </div>
            </div>
          </section>
          <Gear />
        </Main>

    </>
  )
}

export default Home;
